export const toothsOptions = [
  { label: 'Inc. Central Sup. Dir. (1)', value: '1' },
  { label: 'Inc. Central Sup. Esq. (2)', value: '2' },
  { label: 'Inc. Lateral Sup. Dir. (3)', value: '3' },
  { label: 'Inc. Lateral Sup. Esq. (4)', value: '4' },
  { label: 'Canino Sup. Dir. (5)', value: '5' },
  { label: 'Canino Sup. Esq. (6)', value: '6' },
  { label: '1º Pré-Molar Sup. Dir. (7)', value: '7' },
  { label: '1º Pré-Molar Sup. Esq. (8)', value: '8' },
  { label: '2º Pré-Molar Sup. Dir. (9)', value: '9' },
  { label: '2º Pré-Molar Sup. Esq. (10)', value: '10' },
  { label: '1º Molar Sup. Dir. (11)', value: '11' },
  { label: '1º Molar Sup. Esq. (12)', value: '12' },
  { label: '2º Molar Sup. Dir. (13)', value: '13' },
  { label: '2º Molar Sup. Esq. (14)', value: '14' },
  { label: '3º Molar Sup. Dir. (15)', value: '15' },
  { label: '3º Molar Sup. Esq. (16)', value: '16' },
  { label: 'Inc. Central Inf. Dir. (17)', value: '17' },
  { label: 'Inc. Central Inf. Esq. (18)', value: '18' },
  { label: 'Inc. Lateral Inf. Dir. (19)', value: '19' },
  { label: 'Inc. Lateral Inf. Esq. (20)', value: '20' },
  { label: 'Canino Inf. Dir. (21)', value: '21' },
  { label: 'Canino Inf. Esq. (22)', value: '22' },
  { label: '1º Pré-Molar Inf. Dir. (23)', value: '23' },
  { label: '1º Pré-Molar Inf. Esq. (24)', value: '24' },
  { label: '2º Pré-Molar Inf. Dir. (25)', value: '25' },
  { label: '2º Pré-Molar Inf. Esq. (26)', value: '26' },
  { label: '1º Molar Inf. Dir. (27)', value: '27' },
  { label: '1º Molar Inf. Esq. (28)', value: '28' },
  { label: '2º Molar Inf. Dir. (29)', value: '29' },
  { label: '2º Molar Inf. Esq. (30)', value: '30' },
  { label: '3º Molar Inf. Dir. (31)', value: '31' },
  { label: '3º Molar Inf. Esq. (32)', value: '32' }
];
